// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyButJDWUAdhzzD9i8UQuCO3O50sUc0Wqcc',
    appId: '1:589752798190:web:f6d2c7189c5d5fac9d5cff',
    messagingSenderId: '589752798190',
    projectId: 'ourlap-37c5f',
    authDomain: 'ourlap-37c5f.firebaseapp.com',
    storageBucket: 'ourlap-37c5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM5IsxTLJ_07-r4E55S0aYTnLXjjM-emY',
    appId: '1:589752798190:android:f0a3d37a3f96629d9d5cff',
    messagingSenderId: '589752798190',
    projectId: 'ourlap-37c5f',
    storageBucket: 'ourlap-37c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSn0GJqvKCtuP7lieePmlw-IFq9gjM9nQ',
    appId: '1:589752798190:ios:123f20ce83dad4b89d5cff',
    messagingSenderId: '589752798190',
    projectId: 'ourlap-37c5f',
    storageBucket: 'ourlap-37c5f.appspot.com',
    iosClientId: '589752798190-nn0rehj1i27gdf6s3tt36e91mgeg8e1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourLap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSn0GJqvKCtuP7lieePmlw-IFq9gjM9nQ',
    appId: '1:589752798190:ios:123f20ce83dad4b89d5cff',
    messagingSenderId: '589752798190',
    projectId: 'ourlap-37c5f',
    storageBucket: 'ourlap-37c5f.appspot.com',
    iosClientId: '589752798190-nn0rehj1i27gdf6s3tt36e91mgeg8e1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourLap',
  );
}
